apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gatus.fullname" . }}
  labels: {{- include "gatus.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | trimPrefix "|" | nindent 4  }}