apiVersion: v1
kind: Service
metadata:
  name: {{ template "gatus.fullname" . }}
  labels: {{- include "gatus.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector: {{- include "gatus.labels" . | nindent 4 }}