image:
  repository: twinproduction/gatus
  tag: v5.4.0
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  #ingressClassName: nginx
  # Values can be templated
  annotations: {}
  #  kubernetes.io/ingress.class: nginx
  labels: {}
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example.local-tls
  #    hosts:
  #      - chart-example.local

serviceAccount:
  create: true
  name: gatus

# See https://github.com/TwiN/gatus#configuration
config: {}
