{{ if .Values.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lighthouse
  labels:
    app: lighthouse
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "nodes"
    verbs:
      - "get"
      - "watch"
      - "list"
{{ end }}